name: ci

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Short Commit ID
        id: commit_id
        run: echo "::set-output name=short_commit_id::${GITHUB_SHA::7}"

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: pull and push
      #   run: docker pull ubuntu && docker tag ubuntu thanhmanci/test && docker push thanhmanci/test

      - name: Print Short Commit ID
        run: echo ${{ steps.commit_id.outputs.short_commit_id }}